language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn lerna bootstrap
  - yarn test:ci
jobs:
  include:
    - stage: version
      if: (NOT type IN (pull_request)) AND (branch = master)
      script: "yarn lerna version --conventional-commits --yes --create-release github"
before_deploy:
  - git config --global user.email ${GITHUB_EMAIL}
  - git config --global user.name ${GITHUB_USER}
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/Nasdaq/alfheim.git" > /dev/null 2>&1
  - git checkout master
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: "yarn lerna publish from-git --yes"
  cleanup: false
  on:
    node_js: "10"
    tags: true
notifications:
  email:
    recipients:
      - ${GITHUB_EMAIL}
    on_success: change
    on_failure: always
